// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIsk6PEu51gX2wC74YbFS8n7VOKmqAcKo',
    appId: '1:154307594725:web:c2614f61abebdc8a85c70c',
    messagingSenderId: '154307594725',
    projectId: 'peasy-8f59e',
    authDomain: 'peasy-8f59e.firebaseapp.com',
    storageBucket: 'peasy-8f59e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8_587bkPgK9QUr5k4xSEsobCVATdKqMg',
    appId: '1:154307594725:android:89c006102b63b52285c70c',
    messagingSenderId: '154307594725',
    projectId: 'peasy-8f59e',
    storageBucket: 'peasy-8f59e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs2Y-dn-JtQX8RuDZgimlr_3FxL1INoHU',
    appId: '1:154307594725:ios:a0f60f17944662eb85c70c',
    messagingSenderId: '154307594725',
    projectId: 'peasy-8f59e',
    storageBucket: 'peasy-8f59e.firebasestorage.app',
    iosClientId:
        '154307594725-2io7sapvepl8o823fd7lgbkt6lokl2ag.apps.googleusercontent.com',
    iosBundleId: 'com.peasy.ios',
  );
}
